## ONEHOTENCODER MODEL

### LOAD LIBRARIES

In [1]:
import pandas as pd
from category_encoders import OneHotEncoder
import numpy as np

### CARGA DEL CONJUNTO DE DATOS

In [2]:
df = pd.read_csv('../DATA/full_dataset_5901.csv')
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.mean.cad.I.heavy,cdr3.mean.cad.II.heavy,cdr3.mean.cad.III.heavy,cdr3.mean.cad.IV.heavy,cdr3.mean.cad.V.heavy,cdr3.sd.cad.I.heavy,cdr3.sd.cad.II.heavy,cdr3.sd.cad.III.heavy,cdr3.sd.cad.IV.heavy,cdr3.sd.cad.V.heavy
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,-0.228071,0.118357,-0.918786,0.256429,-0.582643,0.994277,0.994596,2.257378,1.103798,2.081136
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-0.162160,0.614400,0.496000,-0.068720,0.425440,0.773515,0.954202,2.614451,1.011290,1.787852
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,-0.156267,0.144467,0.061667,0.004333,-0.055867,0.902415,1.043997,2.292955,1.117883,1.837475
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,-0.205923,-0.002077,-0.773846,0.254462,-0.629692,1.060486,0.801567,2.097305,1.142792,1.963943
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,0.040769,0.199077,0.047538,-0.193462,-0.101077,0.938036,0.805761,2.589105,1.036866,2.082300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,-0.181882,0.024000,0.341000,0.014294,0.210706,1.059848,0.857962,1.824057,1.129363,1.734456
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,-0.548562,0.270500,-0.427063,0.226687,-0.640500,0.898661,0.872311,1.646348,1.190859,1.524972
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,0.081185,0.593407,-0.660222,-0.010704,-0.537370,0.748201,0.973695,2.765732,0.983485,1.927375
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,-0.233944,0.216111,-0.004389,-0.007500,0.102333,0.891995,1.032438,2.101577,1.054722,1.541812
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,-0.415333,0.409389,-0.799444,0.275111,-0.374444,0.894448,0.909247,2.320634,1.094558,1.784336

In [6]:
### STRING-SPLIT CDR1

In [5]:
cdr1_I = df['cdr1.cad.I.heavy'].str.split(';', expand=True)
cdr1_I.columns = ['cdr1.cad.I.heavy.0', 'cdr1.cad.I.heavy.1', 'cdr1.cad.I.heavy.2', 'cdr1.cad.I.heavy.3',
                  'cdr1.cad.I.heavy.4', 'cdr1.cad.I.heavy.5', 'cdr1.cad.I.heavy.6', 'cdr1.cad.I.heavy.7',
                  'cdr1.cad.I.heavy.8', 'cdr1.cad.I.heavy.9']


df = pd.concat([df, cdr1_I], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr1.cad.I.heavy.0,cdr1.cad.I.heavy.1,cdr1.cad.I.heavy.2,cdr1.cad.I.heavy.3,cdr1.cad.I.heavy.4,cdr1.cad.I.heavy.5,cdr1.cad.I.heavy.6,cdr1.cad.I.heavy.7,cdr1.cad.I.heavy.8,cdr1.cad.I.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,-0.384,-1.337,-1.239,-1.337,-0.228,-0.228,0.945,0.26,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-0.384,0.26,-0.032,-1.006,-0.032,-0.228,0.26,-0.384,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,-0.384,-1.006,-0.032,-1.337,-0.228,-0.228,0.945,0.26,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,-0.384,-1.019,-0.032,-1.337,-0.228,-0.228,0.945,0.26,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,-0.384,-1.006,-0.032,-1.337,-0.228,-0.228,0.945,0.26,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,-0.384,0.26,-0.032,-1.006,-0.032,-0.228,0.26,0.26,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,-0.384,1.357,-0.032,-1.019,-0.228,-0.384,0.26,0.26,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,-0.384,-1.006,-0.032,-1.006,-0.228,1.05,0.26,0.26,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,-0.384,-1.006,-0.032,-1.006,-0.228,-0.228,-0.228,-0.591,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,-0.384,-1.019,-0.032,-1.337,-0.228,-0.228,0.945,0.26,None,None

In [7]:
cdr1_II = df['cdr1.cad.II.heavy'].str.split(';', expand=True)
cdr1_II.columns = ['cdr1.cad.II.heavy.0','cdr1.cad.II.heavy.1','cdr1.cad.II.heavy.2','cdr1.cad.II.heavy.3',
                'cdr1.cad.II.heavy.4','cdr1.cad.II.heavy.5','cdr1.cad.II.heavy.6','cdr1.cad.II.heavy.7',
                'cdr1.cad.II.heavy.8','cdr1.cad.II.heavy.9']


df = pd.concat([df, cdr1_II], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr1.cad.II.heavy.0,cdr1.cad.II.heavy.1,cdr1.cad.II.heavy.2,cdr1.cad.II.heavy.3,cdr1.cad.II.heavy.4,cdr1.cad.II.heavy.5,cdr1.cad.II.heavy.6,cdr1.cad.II.heavy.7,cdr1.cad.II.heavy.8,cdr1.cad.II.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,1.652,-0.279,-0.547,-0.279,1.399,1.399,0.828,0.83,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,1.652,0.83,0.326,-0.59,0.326,1.399,0.83,1.652,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,1.652,-0.59,0.326,-0.279,1.399,1.399,0.828,0.83,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,1.652,-0.987,0.326,-0.279,1.399,1.399,0.828,0.83,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,1.652,-0.59,0.326,-0.279,1.399,1.399,0.828,0.83,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,1.652,0.83,0.326,-0.59,0.326,1.399,0.83,0.83,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,1.652,-1.453,0.326,-0.987,1.399,1.652,0.83,0.83,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,1.652,-0.59,0.326,-0.59,1.399,0.302,0.83,0.83,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,1.652,-0.59,0.326,-0.59,1.399,1.399,1.399,-1.302,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,1.652,-0.987,0.326,-0.279,1.399,1.399,0.828,0.83,None,None

In [8]:
cdr1_III = df['cdr1.cad.III.heavy'].str.split(';', expand=True)
cdr1_III.columns = ['cdr1.cad.III.heavy.0','cdr1.cad.III.heavy.1','cdr1.cad.III.heavy.2','cdr1.cad.III.heavy.3',
                'cdr1.cad.III.heavy.4','cdr1.cad.III.heavy.5','cdr1.cad.III.heavy.6','cdr1.cad.III.heavy.7',
                'cdr1.cad.III.heavy.8','cdr1.cad.III.heavy.9']
df = pd.concat([df, cdr1_III], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr1.cad.III.heavy.0,cdr1.cad.III.heavy.1,cdr1.cad.III.heavy.2,cdr1.cad.III.heavy.3,cdr1.cad.III.heavy.4,cdr1.cad.III.heavy.5,cdr1.cad.III.heavy.6,cdr1.cad.III.heavy.7,cdr1.cad.III.heavy.8,cdr1.cad.III.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,1.33,-0.544,2.131,-0.544,-4.76,-4.76,1.299,3.097,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,1.33,3.097,2.213,1.891,2.213,-4.76,3.097,1.33,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,1.33,1.891,2.213,-0.544,-4.76,-4.76,1.299,3.097,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,1.33,-1.505,2.213,-0.544,-4.76,-4.76,1.299,3.097,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,1.33,1.891,2.213,-0.544,-4.76,-4.76,1.299,3.097,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,1.33,3.097,2.213,1.891,2.213,-4.76,3.097,3.097,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,1.33,1.477,2.213,-1.505,-4.76,1.33,3.097,3.097,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,1.33,1.891,2.213,1.891,-4.76,-3.656,3.097,3.097,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,1.33,1.891,2.213,1.891,-4.76,-4.76,-4.76,-0.733,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,1.33,-1.505,2.213,-0.544,-4.76,-4.76,1.299,3.097,None,None

In [9]:
cdr1_IV = df['cdr1.cad.IV.heavy'].str.split(';', expand=True)
cdr1_IV.columns = ['cdr1.cad.IV.heavy.0','cdr1.cad.IV.heavy.1','cdr1.cad.IV.heavy.2','cdr1.cad.IV.heavy.3',
                'cdr1.cad.IV.heavy.4','cdr1.cad.IV.heavy.5','cdr1.cad.IV.heavy.6','cdr1.cad.IV.heavy.7',
                'cdr1.cad.IV.heavy.8','cdr1.cad.IV.heavy.9']


df = pd.concat([df, cdr1_IV], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr1.cad.IV.heavy.0,cdr1.cad.IV.heavy.1,cdr1.cad.IV.heavy.2,cdr1.cad.IV.heavy.3,cdr1.cad.IV.heavy.4,cdr1.cad.IV.heavy.5,cdr1.cad.IV.heavy.6,cdr1.cad.IV.heavy.7,cdr1.cad.IV.heavy.8,cdr1.cad.IV.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,1.045,1.242,0.393,1.242,0.67,0.67,-0.169,-0.838,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,1.045,-0.838,0.908,-0.397,0.908,0.67,-0.838,1.045,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,1.045,-0.397,0.908,1.242,0.67,0.67,-0.169,-0.838,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,1.045,1.266,0.908,1.242,0.67,0.67,-0.169,-0.838,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,1.045,-0.397,0.908,1.242,0.67,0.67,-0.169,-0.838,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,1.045,-0.838,0.908,-0.397,0.908,0.67,-0.838,-0.838,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,1.045,0.113,0.908,1.266,0.67,1.045,-0.838,-0.838,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,1.045,-0.397,0.908,-0.397,0.67,-0.259,-0.838,-0.838,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,1.045,-0.397,0.908,-0.397,0.67,0.67,0.67,1.57,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,1.045,1.266,0.908,1.242,0.67,0.67,-0.169,-0.838,None,None

In [10]:
cdr1_V = df['cdr1.cad.V.heavy'].str.split(';', expand=True)
cdr1_V.columns = ['cdr1.cad.V.heavy.0','cdr1.cad.V.heavy.1','cdr1.cad.V.heavy.2','cdr1.cad.V.heavy.3',
                'cdr1.cad.V.heavy.4','cdr1.cad.V.heavy.5','cdr1.cad.V.heavy.6','cdr1.cad.V.heavy.7',
                'cdr1.cad.V.heavy.8','cdr1.cad.V.heavy.9']


df = pd.concat([df, cdr1_V], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr1.cad.V.heavy.0,cdr1.cad.V.heavy.1,cdr1.cad.V.heavy.2,cdr1.cad.V.heavy.3,cdr1.cad.V.heavy.4,cdr1.cad.V.heavy.5,cdr1.cad.V.heavy.6,cdr1.cad.V.heavy.7,cdr1.cad.V.heavy.8,cdr1.cad.V.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,2.064,-1.262,0.816,-1.262,-2.647,-2.647,0.933,1.512,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,2.064,1.512,1.313,0.412,1.313,-2.647,1.512,2.064,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,2.064,0.412,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,2.064,-0.912,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,2.064,0.412,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,2.064,1.512,1.313,0.412,1.313,-2.647,1.512,1.512,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,2.064,-0.837,1.313,-0.912,-2.647,2.064,1.512,1.512,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,2.064,0.412,1.313,0.412,-2.647,-3.242,1.512,1.512,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,2.064,0.412,1.313,0.412,-2.647,-2.647,-2.647,-0.146,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,2.064,-0.912,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None

In [11]:
df = df.drop(['cdr1.cad.I.heavy', 'cdr1.cad.II.heavy', 'cdr1.cad.III.heavy', 'cdr1.cad.IV.heavy', 'cdr1.cad.V.heavy'], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr1.cad.V.heavy.0,cdr1.cad.V.heavy.1,cdr1.cad.V.heavy.2,cdr1.cad.V.heavy.3,cdr1.cad.V.heavy.4,cdr1.cad.V.heavy.5,cdr1.cad.V.heavy.6,cdr1.cad.V.heavy.7,cdr1.cad.V.heavy.8,cdr1.cad.V.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,2.064,-1.262,0.816,-1.262,-2.647,-2.647,0.933,1.512,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,2.064,1.512,1.313,0.412,1.313,-2.647,1.512,2.064,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,2.064,0.412,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,2.064,-0.912,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,2.064,0.412,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,2.064,1.512,1.313,0.412,1.313,-2.647,1.512,1.512,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,2.064,-0.837,1.313,-0.912,-2.647,2.064,1.512,1.512,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,2.064,0.412,1.313,0.412,-2.647,-3.242,1.512,1.512,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,2.064,0.412,1.313,0.412,-2.647,-2.647,-2.647,-0.146,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,2.064,-0.912,1.313,-1.262,-2.647,-2.647,0.933,1.512,None,None

### STRING-SPLIT CDR2

In [12]:
cdr2_I = df['cdr2.cad.I.heavy'].str.split(';', expand=True)
cdr2_I.columns = ['cdr2.cad.I.heavy.0', 'cdr2.cad.I.heavy.1', 'cdr2.cad.I.heavy.2', 'cdr2.cad.I.heavy.3',
                  'cdr2.cad.I.heavy.4', 'cdr2.cad.I.heavy.5', 'cdr2.cad.I.heavy.6', 'cdr2.cad.I.heavy.7',
                  'cdr2.cad.I.heavy.8', 'cdr2.cad.I.heavy.9']


df = pd.concat([df, cdr2_I], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr2.cad.I.heavy.0,cdr2.cad.I.heavy.1,cdr2.cad.I.heavy.2,cdr2.cad.I.heavy.3,cdr2.cad.I.heavy.4,cdr2.cad.I.heavy.5,cdr2.cad.I.heavy.6,cdr2.cad.I.heavy.7,cdr2.cad.I.heavy.8,cdr2.cad.I.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,-1.239,0.26,-0.228,-0.384,-0.384,-0.228,-0.032,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-1.239,-0.228,-0.591,0.26,0.945,-0.384,0.945,-0.032,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,-1.239,0.26,-0.228,-0.384,-0.384,-0.228,-0.032,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,-1.239,0.26,-0.228,-0.384,-0.384,-0.228,-0.032,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,-1.006,0.26,-0.228,-0.384,-0.384,-0.228,-0.032,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,-1.239,0.945,0.189,-0.228,-0.384,-0.384,-0.384,-0.032,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,-1.239,-0.228,-1.019,1.538,-0.384,-0.032,-0.591,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,-1.239,-0.228,-0.384,-0.384,-0.228,-0.228,-1.006,-0.032,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,-1.239,-1.337,-1.337,-0.384,-0.228,-0.384,0.945,-0.591,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,-1.239,0.26,-0.228,-0.384,-0.384,-0.228,-0.032,None,None,None

In [13]:
cdr2_II = df['cdr2.cad.II.heavy'].str.split(';', expand=True)
cdr2_II.columns = ['cdr2.cad.II.heavy.0', 'cdr2.cad.II.heavy.1', 'cdr2.cad.II.heavy.2', 'cdr2.cad.II.heavy.3',
                  'cdr2.cad.II.heavy.4', 'cdr2.cad.II.heavy.5', 'cdr2.cad.II.heavy.6', 'cdr2.cad.II.heavy.7',
                  'cdr2.cad.II.heavy.8', 'cdr2.cad.II.heavy.9']
df = pd.concat([df, cdr2_II], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr2.cad.II.heavy.0,cdr2.cad.II.heavy.1,cdr2.cad.II.heavy.2,cdr2.cad.II.heavy.3,cdr2.cad.II.heavy.4,cdr2.cad.II.heavy.5,cdr2.cad.II.heavy.6,cdr2.cad.II.heavy.7,cdr2.cad.II.heavy.8,cdr2.cad.II.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,-0.547,0.83,1.399,1.652,1.652,1.399,0.326,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-0.547,1.399,-1.302,0.83,0.828,1.652,0.828,0.326,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,-0.547,0.83,1.399,1.652,1.652,1.399,0.326,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,-0.547,0.83,1.399,1.652,1.652,1.399,0.326,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,-0.59,0.83,1.399,1.652,1.652,1.399,0.326,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,-0.547,0.828,2.081,1.399,1.652,1.652,1.652,0.326,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,-0.547,1.399,-0.987,-0.055,1.652,0.326,-1.302,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,-0.547,1.399,1.652,1.652,1.399,1.399,-0.59,0.326,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,-0.547,-0.279,-0.279,1.652,1.399,1.652,0.828,-1.302,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,-0.547,0.83,1.399,1.652,1.652,1.399,0.326,None,None,None

In [14]:
cdr2_III = df['cdr2.cad.III.heavy'].str.split(';', expand=True)
cdr2_III.columns = ['cdr2.cad.III.heavy.0', 'cdr2.cad.III.heavy.1', 'cdr2.cad.III.heavy.2', 'cdr2.cad.III.heavy.3',
                    'cdr2.cad.III.heavy.4', 'cdr2.cad.III.heavy.5', 'cdr2.cad.III.heavy.6', 'cdr2.cad.III.heavy.7', 
                    'cdr2.cad.III.heavy.8', 'cdr2.cad.III.heavy.9']


df = pd.concat([df, cdr2_III], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr2.cad.III.heavy.0,cdr2.cad.III.heavy.1,cdr2.cad.III.heavy.2,cdr2.cad.III.heavy.3,cdr2.cad.III.heavy.4,cdr2.cad.III.heavy.5,cdr2.cad.III.heavy.6,cdr2.cad.III.heavy.7,cdr2.cad.III.heavy.8,cdr2.cad.III.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,2.131,3.097,-4.76,1.33,1.33,-4.76,2.213,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,2.131,-4.76,-0.733,3.097,1.299,1.33,1.299,2.213,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,2.131,3.097,-4.76,1.33,1.33,-4.76,2.213,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,2.131,3.097,-4.76,1.33,1.33,-4.76,2.213,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,1.891,3.097,-4.76,1.33,1.33,-4.76,2.213,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,2.131,1.299,-1.628,-4.76,1.33,1.33,1.33,2.213,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,2.131,-4.76,-1.505,1.502,1.33,2.213,-0.733,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,2.131,-4.76,1.33,1.33,-4.76,-4.76,1.891,2.213,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,2.131,-0.544,-0.544,1.33,-4.76,1.33,1.299,-0.733,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,2.131,3.097,-4.76,1.33,1.33,-4.76,2.213,None,None,None

In [15]:
cdr2_IV = df['cdr2.cad.IV.heavy'].str.split(';', expand=True)
cdr2_IV.columns = ['cdr2.cad.IV.heavy.0', 'cdr2.cad.IV.heavy.1', 'cdr2.cad.IV.heavy.2', 'cdr2.cad.IV.heavy.3',
                  'cdr2.cad.IV.heavy.4', 'cdr2.cad.IV.heavy.5', 'cdr2.cad.IV.heavy.6', 'cdr2.cad.IV.heavy.7',
                  'cdr2.cad.IV.heavy.8', 'cdr2.cad.IV.heavy.9']


df = pd.concat([df, cdr2_IV], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr2.cad.IV.heavy.0,cdr2.cad.IV.heavy.1,cdr2.cad.IV.heavy.2,cdr2.cad.IV.heavy.3,cdr2.cad.IV.heavy.4,cdr2.cad.IV.heavy.5,cdr2.cad.IV.heavy.6,cdr2.cad.IV.heavy.7,cdr2.cad.IV.heavy.8,cdr2.cad.IV.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,0.393,-0.838,0.67,1.045,1.045,0.67,0.908,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,0.393,0.67,1.57,-0.838,-0.169,1.045,-0.169,0.908,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,0.393,-0.838,0.67,1.045,1.045,0.67,0.908,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,0.393,-0.838,0.67,1.045,1.045,0.67,0.908,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,-0.397,-0.838,0.67,1.045,1.045,0.67,0.908,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,0.393,-0.169,0.421,0.67,1.045,1.045,1.045,0.908,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,0.393,0.67,1.266,0.44,1.045,0.908,1.57,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,0.393,0.67,1.045,1.045,0.67,0.67,-0.397,0.908,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,0.393,1.242,1.242,1.045,0.67,1.045,-0.169,1.57,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,0.393,-0.838,0.67,1.045,1.045,0.67,0.908,None,None,None

In [16]:
cdr2_V = df['cdr2.cad.V.heavy'].str.split(';', expand=True)
cdr2_V.columns = ['cdr2.cad.V.heavy.0', 'cdr2.cad.V.heavy.1', 'cdr2.cad.V.heavy.2', 'cdr2.cad.V.heavy.3',
                  'cdr2.cad.V.heavy.4', 'cdr2.cad.V.heavy.5', 'cdr2.cad.V.heavy.6', 'cdr2.cad.V.heavy.7',
                  'cdr2.cad.V.heavy.8', 'cdr2.cad.V.heavy.9']


df = pd.concat([df, cdr2_V], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr2.cad.V.heavy.0,cdr2.cad.V.heavy.1,cdr2.cad.V.heavy.2,cdr2.cad.V.heavy.3,cdr2.cad.V.heavy.4,cdr2.cad.V.heavy.5,cdr2.cad.V.heavy.6,cdr2.cad.V.heavy.7,cdr2.cad.V.heavy.8,cdr2.cad.V.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,0.816,-2.647,-0.146,1.512,0.933,2.064,0.933,1.313,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,0.412,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,0.816,0.933,-1.392,-2.647,2.064,2.064,2.064,1.313,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,0.816,-2.647,-0.912,2.897,2.064,1.313,-0.146,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,0.816,-2.647,2.064,2.064,-2.647,-2.647,0.412,1.313,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,0.816,-1.262,-1.262,2.064,-2.647,2.064,0.933,-0.146,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None

In [17]:
df = df.drop(['cdr2.cad.I.heavy', 'cdr2.cad.II.heavy', 'cdr2.cad.III.heavy', 'cdr2.cad.IV.heavy', 'cdr2.cad.V.heavy'], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr2.cad.V.heavy.0,cdr2.cad.V.heavy.1,cdr2.cad.V.heavy.2,cdr2.cad.V.heavy.3,cdr2.cad.V.heavy.4,cdr2.cad.V.heavy.5,cdr2.cad.V.heavy.6,cdr2.cad.V.heavy.7,cdr2.cad.V.heavy.8,cdr2.cad.V.heavy.9
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,0.816,-2.647,-0.146,1.512,0.933,2.064,0.933,1.313,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,0.412,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,0.816,0.933,-1.392,-2.647,2.064,2.064,2.064,1.313,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,0.816,-2.647,-0.912,2.897,2.064,1.313,-0.146,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,0.816,-2.647,2.064,2.064,-2.647,-2.647,0.412,1.313,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,0.816,-1.262,-1.262,2.064,-2.647,2.064,0.933,-0.146,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,0.816,1.512,-2.647,2.064,2.064,-2.647,1.313,None,None,None

### STRING-SPLIT CDR3

In [18]:
cdr3_I = df['cdr3.cad.I.heavy'].str.split(';', expand=True)
cdr3_I.columns = ['cdr3.cad.I.heavy.0', 'cdr3.cad.I.heavy.1', 'cdr3.cad.I.heavy.2', 'cdr3.cad.I.heavy.3',
                  'cdr3.cad.I.heavy.4', 'cdr3.cad.I.heavy.5', 'cdr3.cad.I.heavy.6', 'cdr3.cad.I.heavy.7',
                  'cdr3.cad.I.heavy.8', 'cdr3.cad.I.heavy.9', 'cdr3.cad.I.heavy.10','cdr3.cad.I.heavy.11',
                  'cdr3.cad.I.heavy.12', 'cdr3.cad.I.heavy.13', 'cdr3.cad.I.heavy.14', 'cdr3.cad.I.heavy.15',
                  'cdr3.cad.I.heavy.16', 'cdr3.cad.I.heavy.17', 'cdr3.cad.I.heavy.18', 'cdr3.cad.I.heavy.19',
                  'cdr3.cad.I.heavy.20', 'cdr3.cad.I.heavy.21', 'cdr3.cad.I.heavy.22', 'cdr3.cad.I.heavy.23',
                  'cdr3.cad.I.heavy.24', 'cdr3.cad.I.heavy.25', 'cdr3.cad.I.heavy.26', 'cdr3.cad.I.heavy.27', 
                  'cdr3.cad.I.heavy.28', 'cdr3.cad.I.heavy.29', 'cdr3.cad.I.heavy.30','cdr3.cad.I.heavy.31']


df = pd.concat([df, cdr3_I], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.cad.I.heavy.22,cdr3.cad.I.heavy.23,cdr3.cad.I.heavy.24,cdr3.cad.I.heavy.25,cdr3.cad.I.heavy.26,cdr3.cad.I.heavy.27,cdr3.cad.I.heavy.28,cdr3.cad.I.heavy.29,cdr3.cad.I.heavy.30,cdr3.cad.I.heavy.31
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,None,None,None,None,None,None,None,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,1.05,-1.337,-0.595,None,None,None,None,None,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,None,None,None,None,None,None,None,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,None,None,None,None,None,None,None,None,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,None,None,None,None,None,None,None,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,0.26,-0.663,1.05,-1.337,-0.595,None,None,None,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,None,None,None,None,None,None,None,None,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,None,None,None,None,None,None,None,None,None,None

In [19]:
cdr3_II = df['cdr3.cad.II.heavy'].str.split(';', expand=True)
cdr3_II.columns = ['cdr3.cad.II.heavy.0', 'cdr3.cad.II.heavy.1', 'cdr3.cad.II.heavy.2', 'cdr3.cad.II.heavy.3',
                   'cdr3.cad.II.heavy.4', 'cdr3.cad.II.heavy.5', 'cdr3.cad.II.heavy.6', 'cdr3.cad.II.heavy.7',                   
                   'cdr3.cad.II.heavy.8', 'cdr3.cad.II.heavy.9', 'cdr3.cad.II.heavy.10', 'cdr3.cad.II.heavy.11',                   
                   'cdr3.cad.II.heavy.12', 'cdr3.cad.II.heavy.13', 'cdr3.cad.II.heavy.14', 'cdr3.cad.II.heavy.15',                   
                   'cdr3.cad.II.heavy.16', 'cdr3.cad.II.heavy.17', 'cdr3.cad.II.heavy.18', 'cdr3.cad.II.heavy.19',                   
                   'cdr3.cad.II.heavy.20', 'cdr3.cad.II.heavy.21', 'cdr3.cad.II.heavy.22', 'cdr3.cad.II.heavy.23',
                   'cdr3.cad.II.heavy.24', 'cdr3.cad.II.heavy.25', 'cdr3.cad.II.heavy.26', 'cdr3.cad.II.heavy.27',
                   'cdr3.cad.II.heavy.28', 'cdr3.cad.II.heavy.29', 'cdr3.cad.II.heavy.30', 'cdr3.cad.II.heavy.31']

df = pd.concat([df, cdr3_II], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.cad.II.heavy.22,cdr3.cad.II.heavy.23,cdr3.cad.II.heavy.24,cdr3.cad.II.heavy.25,cdr3.cad.II.heavy.26,cdr3.cad.II.heavy.27,cdr3.cad.II.heavy.28,cdr3.cad.II.heavy.29,cdr3.cad.II.heavy.30,cdr3.cad.II.heavy.31
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,None,None,None,None,None,None,None,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,0.302,-0.279,0.009,None,None,None,None,None,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,None,None,None,None,None,None,None,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,None,None,None,None,None,None,None,None,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,None,None,None,None,None,None,None,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,0.83,-1.524,0.302,-0.279,0.009,None,None,None,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,None,None,None,None,None,None,None,None,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,None,None,None,None,None,None,None,None,None,None

In [20]:
cdr3_III = df['cdr3.cad.III.heavy'].str.split(';', expand=True)
cdr3_III.columns = ['cdr3.cad.III.heavy.0', 'cdr3.cad.III.heavy.1', 'cdr3.cad.III.heavy.2', 'cdr3.cad.III.heavy.3',
                    'cdr3.cad.III.heavy.4', 'cdr3.cad.III.heavy.5', 'cdr3.cad.III.heavy.6', 'cdr3.cad.III.heavy.7',
                    'cdr3.cad.III.heavy.8', 'cdr3.cad.III.heavy.9', 'cdr3.cad.III.heavy.10', 'cdr3.cad.III.heavy.11',
                    'cdr3.cad.III.heavy.12', 'cdr3.cad.III.heavy.13', 'cdr3.cad.III.heavy.14', 'cdr3.cad.III.heavy.15',
                    'cdr3.cad.III.heavy.16', 'cdr3.cad.III.heavy.17', 'cdr3.cad.III.heavy.18', 'cdr3.cad.III.heavy.19',
                    'cdr3.cad.III.heavy.20', 'cdr3.cad.III.heavy.21', 'cdr3.cad.III.heavy.22', 'cdr3.cad.III.heavy.23',
                    'cdr3.cad.III.heavy.24', 'cdr3.cad.III.heavy.25', 'cdr3.cad.III.heavy.26', 'cdr3.cad.III.heavy.27',
                    'cdr3.cad.III.heavy.28', 'cdr3.cad.III.heavy.29', 'cdr3.cad.III.heavy.30', 'cdr3.cad.III.heavy.31']


df = pd.concat([df, cdr3_III], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.cad.III.heavy.22,cdr3.cad.III.heavy.23,cdr3.cad.III.heavy.24,cdr3.cad.III.heavy.25,cdr3.cad.III.heavy.26,cdr3.cad.III.heavy.27,cdr3.cad.III.heavy.28,cdr3.cad.III.heavy.29,cdr3.cad.III.heavy.30,cdr3.cad.III.heavy.31
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,None,None,None,None,None,None,None,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-3.656,-0.544,0.672,None,None,None,None,None,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,None,None,None,None,None,None,None,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,None,None,None,None,None,None,None,None,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,None,None,None,None,None,None,None,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,3.097,2.219,-3.656,-0.544,0.672,None,None,None,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,None,None,None,None,None,None,None,None,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,None,None,None,None,None,None,None,None,None,None

In [21]:
cdr3_IV = df['cdr3.cad.IV.heavy'].str.split(';', expand=True)
cdr3_IV.columns = ['cdr3.cad.IV.heavy.0', 'cdr3.cad.IV.heavy.1', 'cdr3.cad.IV.heavy.2', 'cdr3.cad.IV.heavy.3',
                   'cdr3.cad.IV.heavy.4', 'cdr3.cad.IV.heavy.5', 'cdr3.cad.IV.heavy.6', 'cdr3.cad.IV.heavy.7', 
                   'cdr3.cad.IV.heavy.8', 'cdr3.cad.IV.heavy.9', 'cdr3.cad.IV.heavy.10', 'cdr3.cad.IV.heavy.11',
                   'cdr3.cad.IV.heavy.12', 'cdr3.cad.IV.heavy.13', 'cdr3.cad.IV.heavy.14', 'cdr3.cad.IV.heavy.15',
                   'cdr3.cad.IV.heavy.16', 'cdr3.cad.IV.heavy.17', 'cdr3.cad.IV.heavy.18', 'cdr3.cad.IV.heavy.19',
                   'cdr3.cad.IV.heavy.20', 'cdr3.cad.IV.heavy.21', 'cdr3.cad.IV.heavy.22', 'cdr3.cad.IV.heavy.23',
                   'cdr3.cad.IV.heavy.24', 'cdr3.cad.IV.heavy.25', 'cdr3.cad.IV.heavy.26', 'cdr3.cad.IV.heavy.27',
                   'cdr3.cad.IV.heavy.28', 'cdr3.cad.IV.heavy.29', 'cdr3.cad.IV.heavy.30', 'cdr3.cad.IV.heavy.31']


df = pd.concat([df, cdr3_IV], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.cad.IV.heavy.22,cdr3.cad.IV.heavy.23,cdr3.cad.IV.heavy.24,cdr3.cad.IV.heavy.25,cdr3.cad.IV.heavy.26,cdr3.cad.IV.heavy.27,cdr3.cad.IV.heavy.28,cdr3.cad.IV.heavy.29,cdr3.cad.IV.heavy.30,cdr3.cad.IV.heavy.31
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,None,None,None,None,None,None,None,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-0.259,1.242,-2.128,None,None,None,None,None,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,None,None,None,None,None,None,None,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,None,None,None,None,None,None,None,None,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,None,None,None,None,None,None,None,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,-0.838,-1.005,-0.259,1.242,-2.128,None,None,None,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,None,None,None,None,None,None,None,None,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,None,None,None,None,None,None,None,None,None,None

In [22]:
cdr3_V = df['cdr3.cad.V.heavy'].str.split(';', expand=True)
cdr3_V.columns = ['cdr3.cad.V.heavy.0', 'cdr3.cad.V.heavy.1', 'cdr3.cad.V.heavy.2', 'cdr3.cad.V.heavy.3',
                  'cdr3.cad.V.heavy.4', 'cdr3.cad.V.heavy.5', 'cdr3.cad.V.heavy.6', 'cdr3.cad.V.heavy.7',
                  'cdr3.cad.V.heavy.8', 'cdr3.cad.V.heavy.9', 'cdr3.cad.V.heavy.10', 'cdr3.cad.V.heavy.11',
                  'cdr3.cad.V.heavy.12', 'cdr3.cad.V.heavy.13', 'cdr3.cad.V.heavy.14', 'cdr3.cad.V.heavy.15',
                  'cdr3.cad.V.heavy.16', 'cdr3.cad.V.heavy.17', 'cdr3.cad.V.heavy.18', 'cdr3.cad.V.heavy.19',
                  'cdr3.cad.V.heavy.20', 'cdr3.cad.V.heavy.21', 'cdr3.cad.V.heavy.22', 'cdr3.cad.V.heavy.23',
                  'cdr3.cad.V.heavy.24', 'cdr3.cad.V.heavy.25', 'cdr3.cad.V.heavy.26', 'cdr3.cad.V.heavy.27',
                  'cdr3.cad.V.heavy.28', 'cdr3.cad.V.heavy.29', 'cdr3.cad.V.heavy.30', 'cdr3.cad.V.heavy.31']


df = pd.concat([df, cdr3_V], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.cad.V.heavy.22,cdr3.cad.V.heavy.23,cdr3.cad.V.heavy.24,cdr3.cad.V.heavy.25,cdr3.cad.V.heavy.26,cdr3.cad.V.heavy.27,cdr3.cad.V.heavy.28,cdr3.cad.V.heavy.29,cdr3.cad.V.heavy.30,cdr3.cad.V.heavy.31
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,None,None,None,None,None,None,None,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-3.242,-1.262,-0.184,None,None,None,None,None,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,None,None,None,None,None,None,None,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,None,None,None,None,None,None,None,None,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,None,None,None,None,None,None,None,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,1.512,1.212,-3.242,-1.262,-0.184,None,None,None,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,None,None,None,None,None,None,None,None,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,None,None,None,None,None,None,None,None,None,None

In [23]:
df = df.drop(['cdr3.cad.I.heavy', 'cdr3.cad.II.heavy', 'cdr3.cad.III.heavy', 'cdr3.cad.IV.heavy', 'cdr3.cad.V.heavy'], axis=1)
df

,Class,V.GENE.heavy,J.GENE.heavy,D.GENE.heavy,VJ.GENE.heavy,VJ.length.heavy,V.length.heavy,CDR1.length.aa.heavy,CDR2.length.aa.heavy,CDR3.length.aa.heavy,...,cdr3.cad.V.heavy.22,cdr3.cad.V.heavy.23,cdr3.cad.V.heavy.24,cdr3.cad.V.heavy.25,cdr3.cad.V.heavy.26,cdr3.cad.V.heavy.27,cdr3.cad.V.heavy.28,cdr3.cad.V.heavy.29,cdr3.cad.V.heavy.30,cdr3.cad.V.heavy.31
0,Neutralizing,IGHV3-66,IGHJ6,IGHD1-14,IGHV3-66.IGHJ6,347.0,285.0,8.0,7.0,14,...,None,None,None,None,None,None,None,None,None,None
1,Neutralizing,IGHV1-18,IGHJ6,IGHD2-15,IGHV1-18.IGHJ6,350.0,288.0,8.0,8.0,25,...,-3.242,-1.262,-0.184,None,None,None,None,None,None,None
2,Neutralizing,IGHV3-66,IGHJ4,IGHD3-10,IGHV3-66.IGHJ4,333.0,285.0,8.0,7.0,15,...,None,None,None,None,None,None,None,None,None,None
3,Neutralizing,IGHV3-53,IGHJ6,IGHD5-24,IGHV3-53.IGHJ6,343.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
4,Neutralizing,IGHV3-53,IGHJ4,IGHD4-17,IGHV3-53.IGHJ4,332.0,285.0,8.0,7.0,13,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,Neutralizing,IGHV1-46,IGHJ6,IGHD3-9,IGHV1-46.IGHJ6,350.0,288.0,8.0,8.0,17,...,None,None,None,None,None,None,None,None,None,None
5897,Neutralizing,IGHV4-34,IGHJ5,IGHD3-16,IGHV4-34.IGHJ5,335.0,285.0,8.0,7.0,16,...,None,None,None,None,None,None,None,None,None,None
5898,Neutralizing,IGHV3-11,IGHJ6,IGHD6-19,IGHV3-11.IGHJ6,350.0,288.0,8.0,8.0,27,...,1.512,1.212,-3.242,-1.262,-0.184,None,None,None,None,None
5899,Neutralizing,IGHV1-58,IGHJ3,IGHD2-2,IGHV1-58.IGHJ3,337.0,288.0,8.0,8.0,18,...,None,None,None,None,None,None,None,None,None,None
5900,Neutralizing,IGHV3-53,IGHJ6,IGHD2-2,IGHV3-53.IGHJ6,347.0,285.0,8.0,7.0,18,...,None,None,None,None,None,None,None,None,None,None

### TRANFORMACION DE DATOS CATEGORICOS V.GENE.heavy, J.GENE.heavy, D.GENE.heavy, VJ.GENE.heavy

In [24]:
from category_encoders import OneHotEncoder
import joblib

In [25]:
# Columnas categóricas a codificar
columnas_categoricas = ['V.GENE.heavy', 'J.GENE.heavy', 'D.GENE.heavy', 'VJ.GENE.heavy']

In [26]:
# Crear y aplicar OneHotEncoder de una sola vez
encoder = OneHotEncoder(cols=columnas_categoricas, use_cat_names=True)
df = encoder.fit_transform(df)

In [27]:
# Guardar el encoder entrenado para luego usarlo con nuevos datos
joblib.dump(encoder, '../MODELS/onehot_encoder_v1_2025.sav')

['../MODELS/onehot_encoder_v1_2025.sav']